#!/usr/bin/python3                                                                                      
"""app to track who is in space"""

import requests
import pprint
from crayons import blue, red

def prompt_craft_choice():
    while True:
        craft_choice = input("Which craft would you like to see? Enter 1 for Craft 1 (ISS), or 2 for Craft 2 (Tiangong): ")
        if craft_choice == "1":
            return "ISS"
        elif craft_choice == "2":
            return "Tiangong"
        else:
            print("Invalid input. Please select Craft 1 (ISS) or Craft 2 (Tiangong).")

def main():
    astro = requests.get("http://api.open-notify.org/astros.json").json()
    astronauts = astro["people"]

    pprint.pprint(astronauts)

    craft_choice = prompt_craft_choice()

    # create for loop for astronauts
    for a in astronauts:
        craft_color = blue if a["craft"] == "ISS" else red
        print(f'{a["name"]} is on the {craft_color(a["craft"])}')

    print(f'There are {astro["number"]} people in space')

if __name__ == "__main__":
    main()

